### ISSUE TITLE
REPL parser doesn't like uppercase T

### ISSUE THREAD

**Issue by alexeid** [alexeid/graphicalModelSimulation#44]
T = 1.0;

This command results in an error. 

t = 1.0;

This command doesn't.

Probably because of the "truncated" rule in the grammar. I guess uppercase i would also cause the same problem judging from its appearance in the definition of an "interval" in the grammar.

**Comment by rbouckaert** [comment]
I=10; failed as well due to the `interval` rule. I suppressed them with  275bd02 but we could reinstate them if it turns out to be useful.
